### PR TITLE
Fork GitHub actions required to streamline testing PRs with secrets

### PR DESCRIPTION
**Pull request by nineinchnick**
Add actions needed in https://github.com/trinodb/trino/pull/12817/

Don't review actions themselves as they're forks. I added minimum CI jobs to build them and verify that the `dist/index.js` is up-to-date (based on how `actions/setup-node` does this).

### CODE REVIEW

**Comment by hashhar** [comment]
Can "copied"/"preserved" actions live under a separate subdirectory so that it's clear they exist externally + we can have a marker file which indicates what repo + commit it was copied from?

I wish git had something like submodules but where it "vendored" the dependencies instead of using the upstream.

**Comment by nineinchnick** [comment]
I added the reasoning in the README. I think it should be enough, subdirs shouldn't be necessary and they'll be visible when the actions are used which will be noisy.

**Comment by hashhar** [comment]
Please mention the commit of when we forked otherwise it'll be difficult to update them in future.

LGTM otherwise.

**Comment by nineinchnick** [comment]
@hashhar done! I added the exact commits I used and the nearest released version.

**Review by hashhar — APPROVED** [review]
cc: @findepi in case you have opinions

Otherwise I'll merge this later today.

**Comment by findepi** [comment]
thanks @hashhar for the ping.
I don't have an opinion -- it's too complicated to me -- other than let's give this PR a nicer name :)

**Review by hashhar — APPROVED** [review]

**Pull request merged**
